# Image for use in this project

image: ubuntu

# Commands for the build process

install:
  # Install NVM
  - ps: apt-get update
  - ps: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - ps: source ~/.profile
  - ps: nvm --version
  - ps: nvm install 10.14.1
  - ps: nvm use 10.14.1
  - yarn install

test_script:
  - yarn test

# Turn the build off, as otherwise it will try to build a .net project

build: off
