# Image for use in this project

image: ubuntu

# Commands for the build process

install:
  # We have to handle this on our own in this case
  - ps: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - ps: sudo apt-get install -y nodejs
  - yarn install

test_script:
  - node --version
  - yarn test

# Turn the build off, as otherwise it will try to build a .net project

build: off
